blank_issues_enabled: false
contact_links:
  - name: ❓ Support request or technical issue
    url: https://github.com/nolddor/docker-atlassian-plugin-sdk/discussions
    about: We answer all support and technical matters in our GitHub discussions