name: docker-publish

on: 
  workflow_dispatch:

jobs:
  publish-to-dockerhub:
    strategy:
        fail-fast: true
        matrix:
          jdk: [8, 11, 17]

    runs-on: ubuntu-latest
    timeout-minutes: 15


    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: nolddor/atlassian-sdk:${{ matrix.jdk }}-jdk
          build-args: |
            OPENJDK=${{ matrix.jdk }}