name: docker-publish

on: 
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so we have to quote this string
    - cron:  '0 0 * * *'  # every day at midnight

jobs:
  publish-to-dockerhub:
    strategy:
        fail-fast: true
        matrix:
          jdk: [8, 11, 17]

    runs-on: ubuntu-latest
    timeout-minutes: 15


    steps:
      -
        name: Login to Docker Hub
        # https://github.com/docker/login-action
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        # https://github.com/docker/build-push-action
        uses: docker/build-push-action@v5
        with:
          pull: true
          push: true
          tags: nolddor/atlassian-sdk:${{ matrix.jdk }}-jdk
          build-args: |
            OPENJDK=${{ matrix.jdk }}
